---
- name: initial ubuntu configuration with ansible
  hosts: localhost
  become: yes
  vars:
    # password: '`mkpasswd --method=sha-512 123`'
    user: sammy
  tasks:
    - name: create a new user
      user:
        name: "{{ user }}"
        state: present
        home: /home/{{ user }}
        shell: /bin/bash
        # password: "{{ mkpasswd --method=sha-512 123 }}"
        # password: "{{ upassword | string | password_hash('sha512' }}"
        password: $6$.t1SvAeq/JW$mNkrYUpid.Vc32J9E.AcgptlZ/Wr8O2RvG81EyRNF05blCo783jXP2KFYKzUlq3SYlVwg2gFwsfxG4JgQpj7S.



# sudo apt install whois
# mkpasswd --method=sha-512 123 (123 - is password)
# openssl rand -base64 16