---
- name: initial ubuntu configuration with ansible
  hosts: localhost
  become: yes
  vars:
    - username: sammy
  tasks:
    - name: create a new user
      user:
        name: "{{username}}"
        state: present
        groups: sudo
        home: /home/{{username}}
        shell: /bin/bash
        password: '$6$ia7WnUJHgX73$pWPWXbO8KfJ6CJFubhw.mLVDX0kOl07lAypN2Xe/NPwrAiEUpPv6mMtSnLo.oAoNrDh/lDPnCiYP8Mf2ITSMW0'

    - name: ufw enabled
      ufw:
        state: enabled
        policy: deny
        logging: on

    - name: ufw allow rule
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 22

    - name: transfer public-key to sammy user
      copy:
        src: /home/ubuntu/.ssh
        dest: /home/{{username}}
        owner: "{{username}}"
        group: "{{username}}"

      #sudo rsync --archive --chown=sammy:sammy /home/vagrant/.ssh /home/sammy






  # mkpasswd --method=sha-512