---
- name: Install nginx with ansible on centos system
  hosts: localhost
  become: yes

  tasks:
    - name: installs nginx web server
      yum:
        name: nginx
        state: present
        update_cache: yes
      notify: restarts nginx

    - name: install additional packages
      yum:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - wget
        - unzip
        - nano
        - tmux

  handlers:
    - name: restarts nginx
      service:
        name: nginx
        state: restarted













