Vagrant.configure("2") do |config|

  config.vm.define "nginxinstall" do |nginxinstall|
  
  nginxinstall.vm.box = "ubuntu/bionic64"
	
  nginxinstall.vm.network "private_network", ip: "192.168.40.11"
	
  nginxinstall.vm.provider "virtualbox" do |vb|
   vb.memory = "1024"
	 vb.cpus = 2
   end
   
   nginxinstall.vm.provision "shell", inline: <<-SHELL
    
   apt update
   adduser test03

   SHELL
   
  end
end