---
- name: initial ubuntu configuration using ansible
  hosts: localhost
  become: yes
  vars:
    # password: '`mkpasswd --method=sha-512 123`'
    username: sammy

  tasks:
    - name: create a new user
      user:
        name: "{{username}}"
        state: present
        groups: sudo
        home: /home/{{username}}
        shell: /bin/bash
        password: '$6$ia7WnUJHgX73$pWPWXbO8KfJ6CJFubhw.mLVDX0kOl07lAypN2Xe/NPwrAiEUpPv6mMtSnLo.oAoNrDh/lDPnCiYP8Mf2ITSMW0'

    - name: ufw enabled
      ufw:
        state: enabled
        policy: deny
        logging: on

    - name: ufw allow rule
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 22

    - name: transfer public-key to sammy user
      copy:
        src: /home/ubuntu/.ssh
        dest: /home/{{username}}
        owner: "{{username}}"
        group: "{{username}}"

# sudo apt install whois
# mkpasswd --method=sha-512 123 (123 - is password)
# openssl rand -base64 16




