version: "3.8"
services:
    nginx:
        build:
            context: .
        ports:
            - "88:80"
        volumes:
          - web-data: /var/www/html
        container_name: nginx 

volumes:
  web-data: